open('.gitignore','w').write('.env\n__pycache__/\n*.pyc\n.DS_Store\n.streamlit/\nvenv/\n')

open('config/settings.py','w').write(
'MODEL = "gpt-4o-mini"\n'
'MAX_TOKENS = 400\n'
'TEMPERATURE = 0.6\n'
'MAX_IMAGE_SIZE_KB = 500\n'
'SUPPORTED_FORMATS = ["jpg", "jpeg", "png"]\n'
'APP_NAME = "CropAdvisor"\n'
'APP_TAGLINE = "Farm advice from your field, in plain language."\n'
)

open('render.yaml','w').write(
'services:\n'
'  - type: web\n'
'    name: crop-advisor\n'
'    runtime: python\n'
'    buildCommand: pip install -r requirements.txt\n'
'    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0\n'
'    envVars:\n'
'      - key: OPENAI_API_KEY\n'
'        sync: false\n'
)

open('utils/image_utils.py','w').write(
'import base64\n'
'from PIL import Image\n'
'import io\n'
'from config.settings import MAX_IMAGE_SIZE_KB, SUPPORTED_FORMATS\n'
'\n'
'def validate_image(file_bytes, filename):\n'
'    ext = filename.split(".")[-1].lower()\n'
'    if ext not in SUPPORTED_FORMATS:\n'
'        return False, f"Unsupported format. Use: {\', \'.join(SUPPORTED_FORMATS)}"\n'
'    return True, "ok"\n'
'\n'
'def compress_and_encode(file_bytes):\n'
'    img = Image.open(io.BytesIO(file_bytes))\n'
'    img = img.convert("RGB")\n'
'    output = io.BytesIO()\n'
'    quality = 85\n'
'    img.save(output, format="JPEG", quality=quality)\n'
'    while output.tell() > MAX_IMAGE_SIZE_KB * 1024 and quality > 40:\n'
'        output = io.BytesIO()\n'
'        quality -= 10\n'
'        img.save(output, format="JPEG", quality=quality)\n'
'    return base64.b64encode(output.getvalue()).decode("utf-8")\n'
)

open('agent/crop_agent.py','w').write(
'import os\n'
'from openai import OpenAI\n'
'from config.settings import MODEL, MAX_TOKENS, TEMPERATURE\n'
'from utils.image_utils import compress_and_encode\n'
'\n'
'client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))\n'
'\n'
'def build_prompt(farmer_note="", location="", crop_type=""):\n'
'    context_parts = []\n'
'    if crop_type:\n'
'        context_parts.append(f"Crop: {crop_type}")\n'
'    if location:\n'
'        context_parts.append(f"Location: {location}")\n'
'    if farmer_note:\n'
'        context_parts.append(f"Farmer says: {farmer_note}")\n'
'    context = "\\n".join(context_parts) if context_parts else "No additional context provided."\n'
'    return (\n'
'        "You are a friendly farm advisor helping smallholder farmers in plain, simple English.\\n\\n"\n'
'        f"Context:\\n{context}\\n\\n"\n'
'        "Analyze the crop photo and respond in this exact structure:\\n\\n"\n'
'        "PROBLEM: [What you see - disease, pest, nutrient issue, or healthy]\\n"\n'
'        "SEVERITY: [Low / Medium / High]\\n"\n'
'        "ACTION: [3 simple steps the farmer can take - prioritize cheap and local methods]\\n"\n'
'        "WARNING: [One thing NOT to do]\\n\\n"\n'
'        "Keep every answer short. Farmers may have low literacy. Be direct."\n'
'    )\n'
'\n'
'def analyze_crop(image_bytes, farmer_note="", location="", crop_type=""):\n'
'    try:\n'
'        base64_image = compress_and_encode(image_bytes)\n'
'        prompt = build_prompt(farmer_note, location, crop_type)\n'
'        response = client.chat.completions.create(\n'
'            model=MODEL,\n'
'            messages=[{\n'
'                "role": "user",\n'
'                "content": [\n'
'                    {"type": "text", "text": prompt},\n'
'                    {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}}\n'
'                ]\n'
'            }],\n'
'            max_tokens=MAX_TOKENS,\n'
'            temperature=TEMPERATURE\n'
'        )\n'
'        return response.choices[0].message.content.strip()\n'
'    except Exception as e:\n'
'        return f"Analysis failed: {str(e)}"\n'
)

open('app.py','w').write(
'import streamlit as st\n'
'import os\n'
'from dotenv import load_dotenv\n'
'from agent.crop_agent import analyze_crop\n'
'from utils.image_utils import validate_image\n'
'from config.settings import APP_NAME, APP_TAGLINE, SUPPORTED_FORMATS\n'
'\n'
'load_dotenv()\n'
'\n'
'st.set_page_config(page_title=APP_NAME, page_icon="🌱", layout="centered")\n'
'st.title(f"🌱 {APP_NAME}")\n'
'st.caption(APP_TAGLINE)\n'
'\n'
'uploaded_file = st.file_uploader("Upload a photo of your plant or leaf", type=SUPPORTED_FORMATS)\n'
'\n'
'col1, col2 = st.columns(2)\n'
'with col1:\n'
'    crop_type = st.text_input("Crop type", placeholder="e.g. Maize, Tomato, Cassava")\n'
'with col2:\n'
'    location = st.text_input("Your location", placeholder="e.g. Kano, Nigeria")\n'
'\n'
'farmer_note = st.text_area("Anything else?", placeholder="e.g. Leaves started turning yellow 3 days ago", height=80)\n'
'\n'
'if st.button("Analyze Crop 🔍"):\n'
'    if not uploaded_file:\n'
'        st.warning("Please upload a photo first.")\n'
'    else:\n'
'        file_bytes = uploaded_file.read()\n'
'        valid, msg = validate_image(file_bytes, uploaded_file.name)\n'
'        if not valid:\n'
'            st.error(msg)\n'
'        else:\n'
'            with st.spinner("Analyzing your crop..."):\n'
'                result = analyze_crop(file_bytes, farmer_note=farmer_note, location=location, crop_type=crop_type)\n'
'            st.markdown("---")\n'
'            st.markdown("### Analysis")\n'
'            st.markdown(result)\n'
'\n'
'st.markdown("---")\n'
'st.caption("CropAdvisor - For smallholder farmers - Powered by AI")\n'
)

print("All files written successfully.")
